# Generated by Django 4.2.6 on 2024-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learn', '0005_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
