# Generated by Django 4.2.6 on 2024-03-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learn', '0007_language_course_certificate_course_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
