# Generated by Django 4.2.6 on 2024-03-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learn', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.TimeField(null=True),
        ),
    ]
