# Generated by Django 4.2.6 on 2024-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learn', '0011_alter_video_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.FloatField(null=True),
        ),
    ]
